# Custom config for scss-lint
# Find an example of all options here: https://github.com/causes/scss-lint/blob/master/config/default.yml

exclude:
    - 'style.css'
    - 'vendor/**'

linters:
  Indentation:
    enabled: true
    width: 4

  PropertySortOrder:
    order: concentric

  SelectorDepth:
    enabled: true
    max_depth: 4

  StringQuotes:
    style: double_quotes

  NameFormat:
    enabled: false
    convention: BEM

  TrailingSemicolonAfterPropertyValue:
    enabled: false

  SingleLinePerSelector:
    exclude:
      - 'base/_reset.scss'

  StringQuotes:
    style: single_quotes

  DuplicateProperty:
    exclude:
      - 'base/_reset.scss'